{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  rules:
  {{- range .Values.ingress.hostnames }}
  - host: {{ . | quote }}
    http:
      paths:
      - backend:
          service:
            name: {{ $.Release.Name }}
            port:
              name: http
        pathType: Prefix
        path: /
  {{- end }}
  {{- if .Values.ingress.tls }}
  tls:
  - hosts: {{ .Values.ingress.hostnames | toJson }}
    secretName: {{ .Release.Name }}-cert
  {{- end }}
{{- end }}

