{{- $secret := lookup "v1" "Secret" .Release.Namespace (printf "%s-secret" .Release.Name ) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "labels" . | nindent 4 }}
type: Opaque
data:
  {{ if $secret.data }}
  session: {{ $secret.data.session }}
  {{- else }}
  session: {{ randAlphaNum 32 | b64enc }}
  {{- end }}
  {{- if $secret.data }}
  passrecovery: {{ $secret.data.passrecovery }}
  {{- else }}
  passrecovery: {{ randAlphaNum 32 | b64enc }}
  {{- end }}
  {{- if and .Values.agency.companies.enabled (not .Values.agency.companies.shared_secret.source) }}
  shared_secret: {{ .Values.agency.companies.shared_secret.value }}
  {{- end }}