apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-api
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  ports:
  - name: api
    port: 80
    targetPort: api
  selector:
    {{- include "selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: api
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-frontend
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  ports:
  - name: frontend
    port: 80
    targetPort: frontend
  selector:
    {{- include "selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
  type: ClusterIP